<?php
use Illuminate\Support\Facades\Route;
Route::get('/', 'App\Http\Controllers\HomeController@index')->name("home.index");
Route::get('/about', 'App\Http\Controllers\HomeController@about')->name("home.about");
Route::get('/cart', 'App\Http\Controllers\CartController@index')->name("home.cart");
Route::get('/products', 'App\Http\Controllers\ProductController@index')->name("product.index");
Route::get('/products/page/{page}', 'App\Http\Controllers\ProductController@indexpage')->name('product.index.page');
Route::get('/products/{id}', 'App\Http\Controllers\ProductController@show')->name("product.show");
Route::get('/admin', 'App\Http\Controllers\Admin\AdminHomeController@index')->name("admin.home.index");
Route::get('/admin/products', 'App\Http\Controllers\Admin\AdminProductController@index')->name("admin.product.index");
Route::post('/admin/products/store', 'App\Http\Controllers\Admin\AdminProductController@store')->name("admin.product.store");
Route::delete('/admin/products/{id}/delete','App\Http\Controllers\Admin\AdminProductController@delete')->name("admin.product.delete");
Route::get('/admin/products/{id}/edit','App\Http\Controllers\Admin\AdminProductController@edit')->name("admin.product.edit");
Route::put('/admin/products/{id}/update','App\Http\Controllers\Admin\AdminProductController@update')->name("admin.product.update");
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Auth::routes();
Auth::routes();
Route::get('/products/add/{id}', 'App\Http\Controllers\CartController@add');
Route::get('/products/del/{id}', 'App\Http\Controllers\CartController@del');
Route::get('/admin/del/{id}', 'App\Http\Controllers\Admin\AdminProductController@delete');
Route::get('/cart/add/{totalprice}/{totalgame}', 'App\Http\Controllers\CartController@addcart')->name("home.cart.add");
Route::get('/admin/add/{id}/{name}/{dep}/{img}/{price}', 'App\Http\Controllers\Admin\AdminProductController@addnew');
